# Generated by Django 2.1.3 on 2019-02-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190221_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_actors',
            field=models.CharField(max_length=512),
        ),
    ]
