# Generated by Django 2.1.3 on 2019-02-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190221_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_actors',
            field=models.CharField(max_length=1024),
        ),
    ]
