# Generated by Django 2.1.3 on 2019-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190221_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_swiftwriter',
            field=models.CharField(max_length=256),
        ),
    ]
