# Generated by Django 2.1.3 on 2019-02-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20190221_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_rating',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_actors',
            field=models.CharField(max_length=2048),
        ),
    ]
