# Generated by Django 2.1.3 on 2019-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20190222_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_aliasname',
            field=models.CharField(max_length=64),
        ),
    ]
