# Generated by Django 2.1.3 on 2019-02-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20190222_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_capture',
            field=models.CharField(max_length=2048),
        ),
    ]
