# Generated by Django 2.1.3 on 2019-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20190222_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_aliasname',
            field=models.CharField(max_length=256),
        ),
    ]
